name: core_kit
description: Core Kit for sharing cross all apps
version: 0.0.1

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  cherry_toast: ^1.0.3
  dio: ^4.0.4
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_inappwebview: ^5.3.2
  flutter_svg: ^1.0.3
  lottie: ^1.2.1
  package_info_plus: ^1.3.0
  reorderables: ^0.4.2
  url_launcher: ^6.0.18
  pretty_dio_logger: ^1.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  build_resolvers: ^2.0.6
  flutter_gen_runner: ^4.1.5

flutter_gen:
  output: lib/src/ui/assets/
  line_length: 120

  integrations:
    flutter_svg: true

  assets:
    enabled: true
    package_parameter_enabled: true
  
flutter:
  # When adding assets 
  # 1- Run flutter pub get && flutter pub run build_runner build
  # 2- Add the file name to lib/src/assets/assets.dart
  assets:
    - assets/images/
    - assets/animation/
    - assets/icons/

  plugin:
    platforms:
      ios:
        pluginClass: MobileCoreKitPlugin